# Generated by Django 6.0.3 on 2026-03-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app2login',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
