# Generated by Django 6.0.3 on 2026-04-01 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_app2login_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='App2Login',
        ),
        migrations.AddField(
            model_name='app2data',
            name='department',
            field=models.CharField(blank=True, choices=[('Cloud', 'Cloud'), ('IT', 'IT'), ('Networking', 'Networking')], default='IT', max_length=20),
        ),
        migrations.AddField(
            model_name='app2data',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='app2data',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='app2data',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='app2data',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='app2data',
            name='role',
            field=models.CharField(blank=True, choices=[('Cloud Engineer', 'Cloud Engineer'), ('DevOps Engineer', 'DevOps Engineer'), ('Cloud Architect', 'Cloud Architect'), ('Software Developer', 'Software Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Data Analyst/Data Scientist', 'Data Analyst/Data Scientist'), ('Network Engineer', 'Network Engineer'), ('Network Administrator', 'Network Administrator')], default='Software Developer', max_length=40),
        ),
        migrations.AddField(
            model_name='app2data',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='app2data',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='app2data',
            name='description',
        ),
        migrations.RemoveField(
            model_name='app2data',
            name='title',
        ),
        migrations.AlterModelOptions(
            name='app2data',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='app2data',
            unique_together={('user', 'department', 'role')},
        ),
    ]
